"""Document tree models for PageIndex-style hierarchical RAG."""

from __future__ import annotations

from pydantic import BaseModel, Field


class DocTreeNode(BaseModel):
    """A node in the document structure tree.

    Leaf nodes contain actual text content.
    Interior nodes contain a summary (generated by LLM) and children.
    The root node represents the entire document.
    """

    id: str  # unique node id within the tree (e.g. "n0", "n0.1", "n0.1.2")
    title: str  # heading text (or "Root" / "Untitled Section")
    level: int = 0  # heading level: 0 = root, 1 = h1, 2 = h2, etc.
    summary: str = ""  # LLM-generated summary (empty until summarized)
    content: str = ""  # concatenated leaf text (only for leaf nodes)
    page_start: int = 0
    page_end: int = 0
    element_count: int = 0  # number of original structured elements in this subtree
    children: list[DocTreeNode] = Field(default_factory=list)

    @property
    def is_leaf(self) -> bool:
        return len(self.children) == 0

    def leaf_nodes(self) -> list[DocTreeNode]:
        """Collect all leaf nodes under this subtree."""
        if self.is_leaf:
            return [self]
        leaves = []
        for child in self.children:
            leaves.extend(child.leaf_nodes())
        return leaves

    def all_nodes(self) -> list[DocTreeNode]:
        """Collect all nodes (DFS pre-order)."""
        nodes = [self]
        for child in self.children:
            nodes.extend(child.all_nodes())
        return nodes

    def total_content_length(self) -> int:
        """Total character count of all leaf content in this subtree."""
        if self.is_leaf:
            return len(self.content)
        return sum(c.total_content_length() for c in self.children)


class DocTree(BaseModel):
    """Complete document tree for one literature entry."""

    literature_id: str
    title: str = ""  # Document title
    node_count: int = 0
    leaf_count: int = 0
    summaries_generated: bool = False  # True after LLM summarization pass
    root: DocTreeNode
